### ISSUE TITLE
Nice page

### ISSUE THREAD

**Issue by diegosaul402** [salvadorJimenez/MHAssignment1#1]
Hi Salvador,
I really like your page, I think it has great style & colors, good use of custom fonts.
I only "issue" I could see, is that your profile image gets very big when I shrinks the window, should work that way?. The footer has the same issue.
About git, I think you should use to control your projects, 2 commits do not reflect how you do your work.

**Comment by salvadorJimenez** [comment]
I fixed the issue that you mention in your comments, and respect about how i use git you're right, maybe my commits do not reflect how i work, so i will make commits about important changes so thanks for your feedback :)
