### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by Balthair94** [salvadorJimenez/MHAssignment1#3]
Stop the video at since the beginning.

**Comment by salvadorJimenez** [comment]
:c ok i will stop the music :c, but i have to say that 3 or the comments really like the music video well i'm just saying

**Comment by Balthair94** [comment]
Hahahaha it wasn't with bad intentions. I just never likes pages with music. But i have to admit that is a good song.

**Comment by salvadorJimenez** [comment]
:c jajajaja naa it's not a problem, thank you for your feedback :)
